version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: systems.manifold:manifold-all
    versions:
    - 2020.1.46
    - 2020.1.47
    - 2020.1.51
    - 2021.1.0
    - 2021.1.1
    - 2021.1.10
    - 2021.1.3
    - 2021.1.4
    - 2021.1.5
    - 2021.1.7
    - 2021.1.9
  - dependency-name: org.assertj:assertj-core
    versions:
    - 3.19.0
  - dependency-name: com.google.errorprone:error_prone_core
    versions:
    - 2.5.1
  - dependency-name: junit:junit
    versions:
    - 4.13.1
  - dependency-name: org.codehaus.plexus:plexus-compiler-manager
    versions:
    - 2.8.6
  - dependency-name: org.codehaus.plexus:plexus-compiler-api
    versions:
    - 2.8.6
  - dependency-name: org.codehaus.plexus:plexus-compiler-javac-errorprone
    versions:
    - 2.8.6
